name: intervals
description: Provides classes to work with intervals
version: 0.2.0
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/appsup-dart/interval

dev_dependencies:
  test: any
