name: intervals
description: Provides classes to work with intervals
version: 0.2.0-beta.1
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/appsup-dart/interval

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.30
